### ISSUE TITLE
cross-attention layers

### ISSUE THREAD

**Issue by zghhui** [soCzech/ShowHowTo#1]
Hi, dear author, thank you for your efforts in producing this outstanding work.

In this paper, you mentioned: **To guide the generation process to the desired visual instruction sequence, each frame $\(i\)$ in the sequence attends to its prompt $\(\tau_i\)$ via cross-attention layers of the U-Net.** However, I couldn't find the implementation code for this part in the repository. Could you kindly point me to where it is? I would greatly appreciate it.

**Comment by soCzech** [comment]
See the `SpatialTransformer` class.

**Comment by zghhui** [comment]
I understand what you mean, but the attention.py file is basically the same as dynamicrafter. I didn't find out how you calculated cross attention for each frame and each prompt.

**Comment by soCzech** [comment]
Yes, the code is basically the same. But DynamiCrafter uses the same single prompt for the whole sequence. We use different prompts for each frame.

See the code here: https://github.com/soCzech/ShowHowTo/blob/main/predict.py#L33-L38

**Comment by zghhui** [comment]
Thank you for your response, which helpes me solve this problem. Wish you good luck!🫡
