### ISSUE TITLE
download_weights.sh error！

### ISSUE THREAD

**Issue by arenxxxe** [soCzech/ShowHowTo#2]
(showhowto) user@user:~/code1/chk23/2024/ShowHowTo$ ./download_weights.sh
Downloading ShowHowTo weights ... ERROR ✗
(showhowto) user@user:~/code1/chk23/2024/ShowHowTo$ chmod +x download_weights.sh
(showhowto) user@user:~/code1/chk23/2024/ShowHowTo$ ./download_weights.sh
Downloading ShowHowTo weights ... ERROR ✗
(showhowto) user@user:~/code1/chk23/2024/ShowHowTo$ wget https://data.ciirc.cvut.cz/public/projects/2024ShowHowTo/weights/showhowto_2to8steps.pt
--2024-12-08 16:16:00--  https://data.ciirc.cvut.cz/public/projects/2024ShowHowTo/weights/showhowto_2to8steps.pt
正在连接 127.0.0.1:7890... 已连接。
错误: 无法验证 data.ciirc.cvut.cz 的由 “CN=R10,O=Let's Encrypt,C=US” 颁发的证书:
  无法本地校验颁发者的权限。
要以不安全的方式连接至 data.ciirc.cvut.cz，使用“--no-check-certificate”。
(showhowto) user@user:~/code1/chk23/2024/ShowHowTo$ wget --no-check-certificate https://data.ciirc.cvut.cz/public/projects/2024ShowHowTo/weights/showhowto_2to8steps.pt
--2024-12-08 16:21:00--  https://data.ciirc.cvut.cz/public/projects/2024ShowHowTo/weights/showhowto_2to8steps.pt
正在连接 127.0.0.1:7890... 已连接。
警告: 无法验证 data.ciirc.cvut.cz 的由 “CN=R10,O=Let's Encrypt,C=US” 颁发的证书:
  无法本地校验颁发者的权限。
已发出 Proxy 请求，正在等待回应... 403 Forbidden
2024-12-08 16:21:01 错误 403：Forbidden。

how to solve?

**Comment by soCzech** [comment]
Should be fixed now, sorry for the inconvenience;)
